### PR TITLE
Jar file of brick-breaker

### PR DESCRIPTION
**Pull request by SamvruthaShaji**

### CODE REVIEW

**Comment by anandbaburajan** [comment]
@SamvruthaShaji Hey! Thanks for the contribution! Looking forward to try out your project soon. I've a few doubts and opinions:

1. Please provide a description in your PR (next time onwards)
2. Since GitHub is used to store your code so that others can check, you should include the source-code of your project (.java files, etc) 
3. Is the project complete already? Because the JAR file contains the whole project right?

Let me know if you've an doubts!

**Comment by SamvruthaShaji** [comment]
Yes the project is ready and we will also include the  src code soon.

**Comment by anandbaburajan** [comment]
> Yes the project is ready and we will also include the src code soon.

@SamvruthaShaji and @Aiswarya-anand, while that sounds great, I'm sorry that we would have to close this PR. 
We request you to make multiple new PRs, one by one, with each having their own logical part making up the whole project. Similar to what I and @BreadGenie mentioned in the group: an initial PR with basic setup/boilerplate code, then new PRs with incremental changes. That would help us to review small parts of your code at a time and also help you to get more familiar with git. Thanks for contributing!

**Comment by SamvruthaShaji** [comment]
So we have to include source code first and then the jar file, is it?

**Comment by anandbaburajan** [comment]
> So we have to include source code first and then the jar file, is it?

You've to make an initial PR with basic stuff.
Then make another PR with the class declarations or something else.
Then make another one with the basic graphics or something else you choose to do next.

Then at the end, after the final review is done, you can include the .jar file for users.

I'm not that familiar with Java (took a course in S3 I think) so feel free to correct me if I'm wrong somewhere! :)
I can't suggest you Java code suggestions, sadly. But I'll suggest the best practices, which are similar for major programming languages.

Sicne your project is over already, you can just split code into meaningful parts and make PRs.

**Comment by SamvruthaShaji** [comment]
Yes,it will be good if we make PR like this way .
Thankyou for the suggestions
We will make the initial PR as soon as possible

**Pull request closed without merging**
